- name: install and start the packages
  hosts: frontend
  become: yes
  tasks:
  - name: install zip
      ansible.builtin.packages:
       name: zip
       state: present

  - name: start zip
      ansible.buitin.packages:
       name: zip
       state: started
       enabled: yes
