- name: install and start the packages
  hosts: frontend
  become: yes
  tasks:
  - name: install 
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start 
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
