- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: devops
    DURATION: 10HRS
    TRAINER: peraiah
  tasks:
  - name: print the course information
    ansible.builtin.debud:
      msg: "course name is: {{ COURSE }}, duration: {{ DURATION }}, trainer: {{ TRAINER }}"