- name: variables in prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: what is your name?
    private: false
  tasks:
  - name: print the cridentials
    ansible.built.debug:
      msg: "username is: {{ username }}"