- name: variables in datatypes
  hosts: local
  connection: local
  vars:
    cousre: "devops with aws"
    duration: 120
    boolen: true
    tools:
    - "linux"
    - python
    - java
    concepts:
      cloud: aws
      cm: ansible
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "course is: {{ course }}, duration: {{ duration }}, tools are: {{ tools }}, concepts: {{ concepts }}"