- name: variables in datatypes
  hosts: local
  connection: local
  vars:
    COURSE: "devops with aws"
    DURATION: 120
    BOOLEN: true
    TOOLS:
    - "linux"
    - python
    - java
    CONCEPTS:
      cloud: aws
      cm: ansible
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "course is: {{ COURSE }}, duration: {{ DURATION }}, tools are: {{ TOOLS }}, concepts: {{ CONCEPTS }}"