- name: variables in conditions
  hosts: local
  connection: local
  vars:
    NUMBER: 7

  tasks:
  - name: less than or not
    ansible.builtin.debug:
      msg: "Given numver is {{ NUMBER }} less than 10"
    when: NUMBER > 10